#pragma once


////////// Content generated by VS wizard //////////
// Some unused commented out

#ifndef VC_EXTRALEAN
#define VC_EXTRALEAN    // Exclude rarely-used stuff from Windows headers
#endif

// Define these before any includes.
//#define _CRT_NON_CONFORMING_SWPRINTFS 1
#define _CRT_SECURE_NO_WARNINGS 1

#include "targetver.h"

#define _ATL_CSTRING_EXPLICIT_CONSTRUCTORS      // some CString constructors will be explicit

// turns off MFC's hiding of some common and often safely ignored warning messages
#define _AFX_ALL_WARNINGS

#include <afxwin.h>         // MFC core and standard components
#include <afxext.h>         // MFC extensions
//#include <afxdisp.h>        // MFC Automation classes

//#ifndef _AFX_NO_OLE_SUPPORT
//#include <afxdtctl.h>           // MFC support for Internet Explorer 4 Common Controls
//#endif
//#ifndef _AFX_NO_AFXCMN_SUPPORT
//#include <afxcmn.h>             // MFC support for Windows Common Controls
//#endif // _AFX_NO_AFXCMN_SUPPORT

#include <afxcontrolbars.h>     // MFC support for ribbons and control bars


#ifdef _UNICODE
#if defined _M_IX86
#pragma comment(linker,"/manifestdependency:\"type='win32' name='Microsoft.Windows.Common-Controls' version='6.0.0.0' processorArchitecture='x86' publicKeyToken='6595b64144ccf1df' language='*'\"")
#elif defined _M_X64
#pragma comment(linker,"/manifestdependency:\"type='win32' name='Microsoft.Windows.Common-Controls' version='6.0.0.0' processorArchitecture='amd64' publicKeyToken='6595b64144ccf1df' language='*'\"")
#else
#pragma comment(linker,"/manifestdependency:\"type='win32' name='Microsoft.Windows.Common-Controls' version='6.0.0.0' processorArchitecture='*' publicKeyToken='6595b64144ccf1df' language='*'\"")
#endif
#endif

////////// Content from original stdafx.h //////////
// Most removed - see original file

#pragma warning(disable: 4996) // Function declared deprecated

#define CONVERTERS

#include <afxrich.h>
//#include <afxpriv.h>

#define HORZ_TEXTOFFSET 15
#define VERT_TEXTOFFSET 5

class CDisplayIC : public CDC
{
public:
    CDisplayIC() { CreateIC(_T("DISPLAY"), NULL, NULL, NULL); }
};

struct CCharFormat : public CHARFORMAT2
{
    CCharFormat() {cbSize = sizeof(CHARFORMAT2);}
    BOOL operator==(CCharFormat& cf);
};

struct CParaFormat : public PARAFORMAT2
{
    CParaFormat() {cbSize = sizeof(_paraformat);}
    BOOL operator==(PARAFORMAT2& pf);
};

#include "doctype.h"
#include "chicdial.h"

////////// Content custom for WordPad11 //////////

// Turns on writing the registry - the original way.
//#define _REGISTER_APP

// Check version mins for building - Basically standardVS2022.
#if _MSC_VER < 1900
#error "MSC version invalid."
#endif

#if WINVER < 0X0A00
#error "WINVER invalid."
#endif

#if _MFC_VER < 0X0E00
#error "_MFC_VER invalid."
#endif

#if _RICHEDIT_VER < 0X0210
#error "_RICHEDIT_VER invalid."
#endif
